### ISSUE TITLE
TODOs Unclear

### ISSUE THREAD

**Issue by NickDaly** [Deevad/peppercarrot_print_book01#2]
What needs to be done for PC-01-english?  What tasks can users who're familiar with Scribus help with?  What particular Scribus skills are needed to complete what parts of the book?

Also, what do contributors need to do to contribute?  Are there particular licenses users need to submit under?

I guess I'm looking for TODO and COPYING files in the repository.

**Comment by Deevad** [comment]
@NickDaly : Hi, and thanks! I'll review the project this morning, and create the TO-DO file.  It's a good idea.
