### ISSUE TITLE
Structure for translations?

### ISSUE THREAD

**Issue by Alkarex** [Deevad/peppercarrot_print_book01#4]
Hello,
We would be happy to make some translations (e.g. in Danish) when this code is ready.
Would it be possible to have a similar approach and folder structure than for the translation of the episodes?

**Comment by Deevad** [comment]
Hey @Alkarex ; Good idea.

I think a plan would be :

* [x] Move every files to the ISO code folder [en] Exept README.md and IMG folder.
* [x] Rebuild relative links in the *.sla files to point to the correct images ( IMG folder )
* [x] Duplicate the folder and rename to [da]
* [x] Search/Replace in the *.sla all [en_] to [da_]
* [x] Change the $lang in the getPages.bash script to "da", and execute it
* [ ] Then edit the *.sla

Do you think you can manage it?
I'll add you permission to modify this repo.

**Comment by Alkarex** [comment]
New structure and scripts https://github.com/Deevad/peppercarrot_print_book/pull/5
